AWSTemplateFormatVersion: '2010-09-09'

Description: Sample CloudFormation template with YAML - SQS Definition

Parameters:
  StackName:
    Description: Target VPC Stack Name
    Type: String
    MinLength: 1
    MaxLength: 255
    AllowedPattern: ^[a-zA-Z][-a-zA-Z0-9]*$
    Default: sample-cloudformation-vpc-1

Resources:
  SampleCloudFormationSQSSampleQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: SampleCloudFormationSampleQueue
      VisibilityTimeout: 30
#      FifoQueue: false
      DelaySeconds: 5
      MaximumMessageSize: 26144
      MessageRetentionPeriod: 345600
      ReceiveMessageWaitTimeSeconds: 0

Outputs:
  SampleCloudFormationSQSSampleQueue:
    Description: SQS Sample Queue.
    Value: !Ref SampleCloudFormationSQSSampleQueue
    Export:
      Name: !Sub ${StackName}-SQSSampleQueue

