AWSTemplateFormatVersion: '2010-09-09'

Description: Sample CloudFormation template with YAML - S3 Bucket Definition

Parameters:
  S3BucketName:
    Description: Type of this BacketName.
    Type: String
    Default: debugroom-sample-cloudformation-bucket

Resources:
  SampleCloudFormationS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${S3BucketName}
      AccessControl: Private
      PublicAccessBlockConfiguration:
        BlockPublicAcls: True
        BlockPublicPolicy: True
        IgnorePublicAcls: True
        RestrictPublicBuckets: True

Outputs:
  SampleCloudFormationS3Bucket:
    Value: !Ref SampleCloudFormationS3Bucket